config/routes.rb
require 'api_constraints'
require 'default_constraints'

Rails.application.routes.draw do

  get '/', to: redirect('/dashboard')

  devise_scope :admin do
    authenticated  do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'admin/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :admins, controllers: { sessions: 'admin/sessions' }, path_names: { sign_in: '', sign_out: 'logout'}

  namespace :admin, path: '/' do
    resources :dashboard, only: [:index]
    namespace :dashboard, path: '/dashboard' do
      resources :products do
        post '/import' => 'products#import', on: :collection, as: :products_import
        resources :images, only: [:destroy]
      end
      resources :brands
      resources :categories
      resources :orders, only: [:index, :destroy]
    end

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products,   only: [:show, :index]
      resources :brands,     only: [:index]
      get 'brands/:name' => 'brands#show'
      resources :categories, only: [:show, :index]
      resources :orders,     only: [:create]
    end
  end
end

app/models/brand.rb
class Brand
  include Mongoid::Document
  include Mongoid::Paperclip

  field :name,          type: String
  field :description,   type: String
  field :slug,          type: String

  has_mongoid_attached_file :image,
                            styles: {
                                thumb: '150x150'
                            }
  do_not_validate_attachment_file_type :image

  has_many :products, inverse_of: :brand

  def image_url
    image.url
  end

end

app/controllers/admin/dashboard/brands_controller.rb
class Admin::Dashboard::BrandsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = paginate(Brand.all)
  end

  def show
  end

  def new
    @brand = Brand.new
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)
    create_slug(@brand, @brand.name)
    if @brand.save
      redirect_to admin_dashboard_brands_url
    else
      render :new
    end
  end

  def update
    create_slug(@brand, brand_params[:name])
    if @brand.update(brand_params)
      redirect_to admin_dashboard_brands_url
    else
      render :edit
    end
  end

  def destroy
    @brand.delete
    admin_dashboard_brands_url
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :description, :image, product_ids: [])
  end
end

app/controllers/admin/dashboard/categories_controller.rb
class Admin::Dashboard::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  def index
    @categories = paginate(Category.all)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_dashboard_categories_url
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_dashboard_categories_url
    else
      render :new
    end
  end

  def destroy
    @category.delete
    redirect_to admin_dashboard_categories_url
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, product_ids: [])
  end
end

app/controllers/admin/dashboard/images_controller.rb
class Admin::Dashboard::ImagesController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    image = Image.find(params[:id])
    if image.destroy
      respond_to :js
    end
  end

  private

  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/admin/dashboard/orders_controller.rb
class Admin::Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
  end
end

app/controllers/admin/dashboard/products_controller.rb
class Admin::Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = paginate(Product.all)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      @product.add_images(product_params[:product_images])
      redirect_to admin_dashboard_products_url
    else
      render :new
    end
  end

  def update
    @product.assign_attributes(product_params)
    binding.pry
    @product.add_images(product_params[:product_images]) if product_params[:product_images].present?
    if @product.save
      redirect_to admin_dashboard_products_url
    else
      render :edit
    end
  end

  def destroy
    @product.delete
    redirect_to admin_dashboard_products_url
  end

  def import

  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
        :name_en,
        :name_ru,
        :description,
        :title,
        :first_notes,
        :second_notes,
        :third_notes,
        :brand_id,
        :version,
        :year,
        :for_man,
        :slug,
        :is_cosmetic,
        category_ids: [],
        product_images: [],
        volumes_attributes: [:id, :_destroy, :value, :price, :old_price]
    )
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_admin!

  def index

  end
end

app/controllers/api/v1/brands_controller.rb
class Api::V1::BrandsController < Api::V1::MainController

  def index
    brands = Brand.all
    render json: brands.to_json(only: [:name, :description, :slug],
                                include: {
                                    products:{
                                        only: [:name_en, :description, :price, :slug],
                                        methods: [:images_url]
                                    }
                                }), status: 201, root: false
  end

  def show
    brand = Brand.find_by(name: params[:name])
    render json: Product.where(brand_id: brand.id).to_json(only: [:name_en, :price, :slug], methods: [:images_url])
  end
end

app/helpers/admin/dashboard/images_helper.rb
module Admin::Dashboard::ImagesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/api/v1/brands_helper.rb
module Api::V1::BrandsHelper
end

app/views/admin/dashboard/brands/_form.haml
.col-md-12
  %section.panel.general
    = form_for [:admin, :dashboard, @brand], html: { id: 'edit_form', multipart: true} do |f|
      .panel-body
        .tab-content
          #home.tab-pane.active
            .row
              .col-md-8.form-group
                = f.label 'Название'
                = f.text_field :name, class: 'form-control', required: true
              .col-md-4.form-group{style: 'float:right;'}
                = f.label 'Товары'
                = f.collection_select :product_ids, Product.all, :id, :name_en,
                      { selected: (@brand.products.map(&:id) unless f.object.new_record?)},
                  {class: 'form-control', multiple: true, size: 14 }
              .col-md-8.form-group
                = f.label 'Ссылка'
                = f.text_field :slug, class: 'form-control'
              .col-md-8.form-group
                = f.label 'Описание'
                = f.text_area :description, class: 'form-control', rows: 4, required: true

            - if !f.object.new_record? && f.object.image.present?
              .row
                .col-md-4
                  .form-group
                    = f.label 'Картинка слайда'
                    = f.file_field :image
                  .form-group{style: 'max-height: 180px; overflow: hidden;padding-top: 24px;'}
                    - if action_name == 'edit' && f.object.image
                      = image_tag f.object.image(:thumb)
            .row
              .col-md-12.form-group
                %label
                  = 'Добавить изображения'
                  = f.file_field :image, accept: 'image/png,image/gif,image/jpeg'

          .row
            .col-md-12{style: ' padding-top: 15px;'}
              = f.submit 'Сохранить!', class: 'btn btn-info'

app/views/admin/dashboard/brands/edit.haml
#contentWrapperWrapper.main-container
  #contentWrapper.section.main{role: 'main', style: 'letter-spacing: 0;'}
    .row
      .col-md-12
        %h3.pull-left Редактирование бренда

    = render 'form'

app/views/admin/dashboard/brands/index.haml
.row{style: 'padding-bottom: 15px;'}
  .col-md-2
    = link_to 'Создать', new_admin_dashboard_brand_url, class: 'pull-left btn btn-success'
.row
  .col-md-12{style: 'min-height: 500px;'}
    %section.panel
      %header.panel-heading
        Все бренды
      .panel-body.table-responsive
        %table.table.table-hover
          .col-md-12#orders_pagination{style: 'text-align:center;'}
            = paginate @brands
          %thead
            %tr
              %th Название
              %th Товаров
              %th
          %tbody#orders
            - @brands.each do |brand|
              %tr
                %td= brand.name
                %td= brand.products.length
                %td
                  = link_to edit_admin_dashboard_brand_url(brand), class: 'btn btn-default btn-xs' do
                    %i.fa.fa-pencil
                  = link_to admin_dashboard_brand_path(brand), method: :delete, class: 'btn btn-default btn-xs',
                          data: {confirm: "Вы уверены что хотите удалить категорию #{brand.name}"} do
                    %i.fa.fa-times

app/views/admin/dashboard/brands/new.haml
#contentWrapperWrapper.main-container
  #contentWrapper.section.main{role: 'main', style: 'letter-spacing: 0;'}
    .row
      .col-md-12
        %h3.pull-left Новый бренд

    = render 'form'