config/routes.rb
require 'api_constraints'
require 'default_constraints'

Rails.application.routes.draw do

  get '/', to: redirect('/dashboard')

  devise_scope :admin do
    authenticated  do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'admin/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :admins, controllers: { sessions: 'admin/sessions' }, path_names: { sign_in: '', sign_out: 'logout'}

  namespace :admin, path: '/' do
    resources :dashboard, only: [:index]
    namespace :dashboard, path: '/dashboard' do
      resources :products do
        post '/import' => 'products#import', on: :collection, as: :products_import
        resources :images, only: [:destroy]
      end
      resources :brands
      resources :categories
      resources :orders, only: [:index, :destroy]
    end

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products,   only: [:show, :index]
      resources :brands,     only: [:index]
      get 'brands/:name' => 'brands#show'
      resources :categories, only: [:show, :index]
      resources :orders,     only: [:create]
    end
  end
end

app/controllers/admin/dashboard/brands_controller.rb
class Admin::Dashboard::BrandsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = paginate(Brand.all)
  end

  def show
  end

  def new
    @brand = Brand.new
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)
    create_slug(@brand, @brand.name)
    if @brand.save
      redirect_to admin_dashboard_brands_url
    else
      render :new
    end
  end

  def update
    create_slug(@brand, brand_params[:name])
    if @brand.update(brand_params)
      redirect_to admin_dashboard_brands_url
    else
      render :edit
    end
  end

  def destroy
    @brand.delete
    admin_dashboard_brands_url
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :description, :image, product_ids: [])
  end
end

app/controllers/admin/dashboard/categories_controller.rb
class Admin::Dashboard::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  def index
    @categories = paginate(Category.all)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_dashboard_categories_url
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_dashboard_categories_url
    else
      render :new
    end
  end

  def destroy
    @category.delete
    redirect_to admin_dashboard_categories_url
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, product_ids: [])
  end
end

app/controllers/admin/dashboard/images_controller.rb
class Admin::Dashboard::ImagesController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    image = Image.find(params[:id])
    if image.destroy
      respond_to :js
    end
  end

  private

  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/admin/dashboard/orders_controller.rb
class Admin::Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
  end
end

app/controllers/admin/dashboard/products_controller.rb
class Admin::Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = paginate(Product.all)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      @product.add_images(product_params[:product_images])
      redirect_to admin_dashboard_products_url
    else
      render :new
    end
  end

  def update
    @product.assign_attributes(product_params)
    binding.pry
    @product.add_images(product_params[:product_images]) if product_params[:product_images].present?
    if @product.save
      redirect_to admin_dashboard_products_url
    else
      render :edit
    end
  end

  def destroy
    @product.delete
    redirect_to admin_dashboard_products_url
  end

  def import

  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
        :name_en,
        :name_ru,
        :description,
        :title,
        :first_notes,
        :second_notes,
        :third_notes,
        :brand_id,
        :version,
        :year,
        :for_man,
        :slug,
        :is_cosmetic,
        category_ids: [],
        product_images: [],
        volumes_attributes: [:id, :_destroy, :value, :price, :old_price]
    )
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_admin!

  def index

  end
end

app/helpers/admin/dashboard/images_helper.rb
module Admin::Dashboard::ImagesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/_header.haml
%header.header
  = link_to 'Панель управления', root_url, class: 'logo'
  / Header Navbar: style can be found in header.less
  %nav.navbar.navbar-static-top{:role => 'navigation'}
    / Sidebar toggle button
    %a.navbar-btn.sidebar-toggle{'data-toggle' => 'offcanvas', :href => '#', :role => 'button'}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-right
      %ul.nav.navbar-nav
        %li.dropdown.user.user-menu
          %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
            %i.fa.fa-user
            %span
              Админ
              %i.caret
          %ul.dropdown-menu.dropdown-custom.dropdown-menu-right
            %li.dropdown-header.text-center Меню
            %li
              = link_to products_import_admin_dashboard_products_url do
                %i.fa.fa-download.fa-fw.pull-right
                Импорт
            %li
              = link_to destroy_admin_session_path, method: :delete do
                %i.fa.fa-ban.fa-fw.pull-right
                Выйти

app/views/admin/dashboard/_side_menu.html.haml
%aside.left-side.sidebar-offcanvas
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel
    .user-panel
      .pull-left.info
        %p{style: 'float:left; padding-right:7px;'}
          = Time.now.to_date.strftime('%d.%m.%Y')
        %p#live_time{style: 'float:left;'}
        %p
          = l Date.today, format: '%A'

    %ul.sidebar-menu
      %li{class: "#{'active' if request.fullpath.include?('products')}" }
        = link_to admin_dashboard_products_url do
          %i.fa.fa-money
          %span Товары
      %li{class: "#{'active' if request.fullpath.include?('brands')}" }
        = link_to admin_dashboard_brands_url do
          %i.fa.fa-money
          %span Бренды
      %li{class: "#{'active' if request.fullpath.include?('categories')}" }
        = link_to admin_dashboard_categories_url do
          %i.fa.fa-money
          %span Категории

app/views/admin/dashboard/index.haml
%div{style:'min-height: 250px;'}