config/routes.rb
require 'api_constraints'
require 'default_constraints'

Rails.application.routes.draw do

  get '/', to: redirect('/dashboard')

  devise_scope :admin do
    authenticated  do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'admin/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :admins, controllers: { sessions: 'admin/sessions' }, path_names: { sign_in: '', sign_out: 'logout'}

  namespace :admin, path: '/' do
    resources :dashboard, only: [:index]
    namespace :dashboard, path: '/dashboard' do
      resources :products do
        post '/import' => 'products#import', on: :collection, as: :products_import
        resources :images, only: [:destroy]
      end
      resources :brands
      resources :categories
      resources :orders, only: [:index, :destroy]
    end

  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products,   only: [:show, :index]
      resources :brands,     only: [:index]
      get 'brands/:name' => 'brands#show'
      resources :categories, only: [:show, :index]
      resources :orders,     only: [:create]
    end
  end
end

app/models/product.rb
class Product
  include Mongoid::Document

  VERSIONS = ['Туалетная вода', 'Парфюмерная вода', 'Масло', 'Тушь']

  attr_accessor :product_images, :options

  field :name_en,       type: String
  field :name_ru,       type: String
  field :description,   type: String
  field :title,         type: String
  field :first_notes,   type: String
  field :second_notes,  type: String
  field :third_notes,   type: String
  field :version,       type: String
  field :is_cosmetic,   type: Boolean, default: false
  field :for_man,       type: Boolean, default: false
  field :year,          type: String
  field :slug,          type: String

  index slug: 1

  embeds_many :volumes
  has_and_belongs_to_many :categories
  has_many   :images

  belongs_to :brand

  accepts_nested_attributes_for :volumes, allow_destroy: true

  def images_url
    images.map {|i| i.file.url}
  end

  def add_images(images)
    images.each { |i| self.images.create(file: i) }
  end
end

app/controllers/admin/dashboard/brands_controller.rb
class Admin::Dashboard::BrandsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = paginate(Brand.all)
  end

  def show
  end

  def new
    @brand = Brand.new
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)
    create_slug(@brand, @brand.name)
    if @brand.save
      redirect_to admin_dashboard_brands_url
    else
      render :new
    end
  end

  def update
    create_slug(@brand, brand_params[:name])
    if @brand.update(brand_params)
      redirect_to admin_dashboard_brands_url
    else
      render :edit
    end
  end

  def destroy
    @brand.delete
    admin_dashboard_brands_url
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :description, :image, product_ids: [])
  end
end

app/controllers/admin/dashboard/categories_controller.rb
class Admin::Dashboard::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  def index
    @categories = paginate(Category.all)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_dashboard_categories_url
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_dashboard_categories_url
    else
      render :new
    end
  end

  def destroy
    @category.delete
    redirect_to admin_dashboard_categories_url
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, product_ids: [])
  end
end

app/controllers/admin/dashboard/images_controller.rb
class Admin::Dashboard::ImagesController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    image = Image.find(params[:id])
    if image.destroy
      respond_to :js
    end
  end

  private

  def image_params
    params.require(:image).permit(:file)
  end
end

app/controllers/admin/dashboard/orders_controller.rb
class Admin::Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
  end
end

app/controllers/admin/dashboard/products_controller.rb
class Admin::Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = paginate(Product.all)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      @product.add_images(product_params[:product_images])
      redirect_to admin_dashboard_products_url
    else
      render :new
    end
  end

  def update
    @product.assign_attributes(product_params)
    binding.pry
    @product.add_images(product_params[:product_images]) if product_params[:product_images].present?
    if @product.save
      redirect_to admin_dashboard_products_url
    else
      render :edit
    end
  end

  def destroy
    @product.delete
    redirect_to admin_dashboard_products_url
  end

  def import

  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
        :name_en,
        :name_ru,
        :description,
        :title,
        :first_notes,
        :second_notes,
        :third_notes,
        :brand_id,
        :version,
        :year,
        :for_man,
        :slug,
        :is_cosmetic,
        category_ids: [],
        product_images: [],
        volumes_attributes: [:id, :_destroy, :value, :price, :old_price]
    )
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_admin!

  def index

  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::MainController

  def index
    # @products = Hash.recursive
    if params[:options]
      category = params[:options][:category] != 'null' ? Category.find_by(name: params[:options][:category]).id : 
	Category.in(name: Category.all.map(&:name)).map(&:id)
      @products = Product.in(category_ids: category)

      if params[:brand]  != 'null' && params[:brand].present?
        brand = Brand.find_by(name: params[:brand])
        @products = @products.where(brand_id: brand.id)
      end
    else
      @products = Product.all
    end
    render json: @products.to_json(methods: [:images_url], include: :brand), root: false
  end

  def show
    respond_with Product.find(params[:name])
  end
end

app/helpers/admin/dashboard/images_helper.rb
module Admin::Dashboard::ImagesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/views/admin/dashboard/products/_form.haml
.col-md-12
  %section.panel.general
    = nested_form_for [:admin, :dashboard, @product], html: { id: 'edit_form', multipart: true} do |f|
      .panel-body
        .tab-content
          #home.tab-pane.active
            .row
              .col-md-12.form-group
                = f.check_box :is_cosmetic, class: 'linear'
                %label Косметика
            .row
              .col-md-6.form-group
                = f.label 'Название на английском'
                = f.text_field :name_en, class: 'form-control', required: true
              .col-md-6.form-group
                = f.label 'Название на русском'
                = f.text_field :name_ru, class: 'form-control'
            .row
              .col-md-1.col-md-offset-11
                = f.link_to_add '+', :volumes, data: {target: '#volume'}, class: 'btn btn-success pull-right'

            #volume
              = f.fields_for :volumes do |volume_builder|
                .row
                  .col-md-3.form-group
                    = volume_builder.label 'Объем'
                    = volume_builder.text_field :value, class: 'form-control'
                  .col-md-3.form-group
                    = volume_builder.label 'Цена без скидки'
                    = volume_builder.text_field :old_price, class: 'form-control'
                  .col-md-3.form-group
                    = volume_builder.label 'Цена со скидкой'
                    = volume_builder.text_field :price, class: 'form-control'
                  .col-md-3.form-group
                    = volume_builder.link_to_remove 'X', class: 'btn btn-danger pull-right',
                      style: 'margin-top: 25px;'



            .row
              .col-md-5.form-group
                = f.label 'Ссылка'
                = f.text_field :slug, class: 'form-control'
              .col-md-3.form-group
                = f.label 'Тип'
                = f.select :version, Product::VERSIONS, {include_blank: 'Нет'}, class: 'form-control'
              .col-md-2.form-group{style: 'text-align:center;'}
                = f.label 'Для мужчин'
                %br
                %div{ style: 'margin-top: 5px;'}
                  = f.check_box :for_man, class: 'normal'
              .col-md-2.form-group
                = f.label 'Бренд'
                = f.collection_select :brand_id, Brand.all, :id, :name,
                      { selected: (@product.brand_id unless f.object.new_record? && f.object.brand.present?),
                      rows: 4}, {class: 'form-control' }
            .row
              .col-md-12.form-group
                = f.label 'Заголовок'
                = f.text_field :title, class: 'form-control'

            .row
              .col-md-9.form-group
                = f.label 'Описание'
                = f.text_area :description, class: 'form-control', rows: 4, required: true
              .col-md-3.form-group
                = f.label 'Категории'
                = f.collection_select :category_ids, Category.all, :id, :name,
                      { selected: (@product.categories.map(&:id) unless f.object.new_record?), rows: 4},
                      {class: 'form-control', multiple: true }
            .row
              .col-md-3.form-group
                = f.label 'Год выпуска'
                = f.text_area :year, class: 'form-control', rows: 3
              .col-md-3.form-group
                = f.label 'Верхние ноты'
                = f.text_area :first_notes, class: 'form-control', rows: 3
              .col-md-3.form-group
                = f.label 'Ноты сердца'
                = f.text_area :second_notes, class: 'form-control', rows: 3
              .col-md-3.form-group
                = f.label 'Базовые ноты'
                = f.text_area :third_notes, class: 'form-control', rows: 3

            - if !f.object.new_record? && @product.images.present?
              .row
                .col-md-12.form-group#images_list{style: 'height: 140px;overflow-x:auto;overflow-y:hidden;white-space:nowrap;'}
                  - @product.images.each do |image|
                    %div#this_image{style: 'display:inline-block;'}
                      .stat
                        .stat-icon{style: 'height:90px;max-height:90px;overflow:hidden;'}
                          = image_tag image.file(:thumb)
                        .stat-info
                          = link_to 'Удалить', admin_dashboard_product_image_path(id: image.id.to_s, product_id: f.object.id), method: :delete, remote: true,
                              id: 'destroy_this_image', data: {confirm: 'Вы уверены?'}, class: 'label label-danger'
            .row
              .col-md-12.form-group
                %label
                  = 'Добавить изображения'
                  = file_field_tag 'product', multiple: true, name: 'product[product_images][]',
                      accept: 'image/png,image/gif,image/jpeg'

          .row
            .col-md-12{style: ' padding-top: 15px;'}
              = f.submit 'Сохранить!', class: 'btn btn-info'

app/views/admin/dashboard/products/edit.haml
#contentWrapperWrapper.main-container
  #contentWrapper.section.main{role: 'main', style: 'letter-spacing: 0;'}
    .row
      .col-md-12
        %h3.pull-left Редактирование товара

    = render 'form'

app/views/admin/dashboard/products/index.haml
.row{style: 'padding-bottom: 15px;'}
  .col-md-2
    = link_to 'Создать', new_admin_dashboard_product_url, class: 'pull-left btn btn-success'
.row
  .col-md-12{style: 'min-height: 500px;'}
    %section.panel
      %header.panel-heading
        Все товары
      .panel-body.table-responsive
        %table.table.table-hover
          .col-md-12#products_pagination{style: 'text-align:center;'}
            = paginate @products
          %thead
            %tr
              %th Название
              %th Бренд
              %th Категория
              %th Цена
              %th
          %tbody#products
            - @products.each do |product|
              %tr
                %td= product.name_en
                %td= product.brand.name if product.brand
                %td= product.categories.map(&:name).join(', ')
                -#%td= number_with_delimiter product.price + ' б.р.' if product.price
                %td
                  = link_to edit_admin_dashboard_product_url(product), class: 'btn btn-default btn-xs' do
                    %i.fa.fa-pencil
                  = link_to admin_dashboard_product_path(product), method: :delete, class: 'btn btn-default btn-xs',
                          data: {confirm: "Вы уверены что хотите удалить товар #{product.name_en}"} do
                    %i.fa.fa-times

app/views/admin/dashboard/products/new.haml
#contentWrapperWrapper.main-container
  #contentWrapper.section.main{role: 'main', style: 'letter-spacing: 0;'}
    .row
      .col-md-12
        %h3.pull-left Новый товар

    = render 'form'